# This file is generated by rake. Do not edit.


module UnixFFI::Struct
  class Passwd < FFI::ManagedStruct
    layout :pw_name, :string, 0,
           :pw_passwd, :string, 8,
           :pw_uid, :int, 16,
           :pw_gid, :int, 20,
           :pw_gecos, :string, 24,
           :pw_dir, :string, 32,
           :pw_shell, :string, 40







    def self.release(ptr)
      Passwd.free_object(ptr)
    end
  end
end

